<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\JK.Platform.Core.Abstraction\JK.Platform.Core.Abstraction.csproj" />
        <ProjectReference Include="..\Core\JK.Platform.Core.BlobStorage\JK.Platform.Core.BlobStorage.csproj" />
        <ProjectReference Include="..\Core\JK.Platform.Core\JK.Platform.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Minio" Version="6.0.3" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="9.0.0" />
    </ItemGroup>
</Project>
