<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.0" />
    <PackageReference Include="StackExchange.Redis.Extensions.System.Text.Json" Version="12.2.0" />
    <PackageReference Include="StackExchange.Redis.Extensions.Core" Version="12.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Platform\Cache\JK.Platform.Cache.Redis\JK.Platform.Cache.Redis.csproj" />
    <ProjectReference Include="..\..\Platform\Core\JK.Platform.Core.Cache\JK.Platform.Core.Cache.csproj" />
  </ItemGroup>

</Project>
