<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Core\JK.Platform.Core.DistributedLock\JK.Platform.Core.DistributedLock.csproj" />
        <ProjectReference Include="..\..\Core\JK.Platform.Core.Abstraction\JK.Platform.Core.Abstraction.csproj" />
        <ProjectReference Include="..\..\Core\JK.Platform.Core\JK.Platform.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DistributedLock.Redis" Version="1.0.3" />
        <PackageReference Include="StackExchange.Redis.Extensions.Core" Version="12.2.0" />
    </ItemGroup>

</Project>
