apiVersion: v1
kind: Secret
metadata:
  name: jk-db-secret
  namespace: jk-three-tier
type: Opaque
stringData:
  POSTGRES_PASSWORD: "6PostgresPassword"

  CONFIGURATION_DB_CONNECTION_STRING: "Host=postgres;Port=5432;Database=jk_configuration;Username=postgres;Password=6PostgresPassword;"
  ORDER_DB_CONNECTION_STRING: "Host=postgres;Port=5432;Database=jk_order;Username=postgres;Password=6PostgresPassword;"
  MESSAGING_DB_CONNECTION_STRING: "Host=postgres;Port=5432;Database=jk_messaging;Username=postgres;Password=6PostgresPassword;"
