apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db-secret.yaml
  - postgres.yaml
  - configuration.yaml
  - order.yaml
  - messaging.yaml
  - frontend.yaml
  - ingress.yaml
  - db-ingress-tcp.yaml
  - migrations-job.yaml
