apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: jk-three-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: jk-order:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: jk-db-secret
                  key: DB_CONNECTION_STRING
            - name: ConfigurationProvider__ServerUrl
              value: "http://configuration:8081"
            - name: GrpcClientConfiguration__UseSecureSslChannel
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: jk-three-tier
spec:
  type: ClusterIP
  selector:
    app: order
  ports:
    - name: http
      port: 8080
      targetPort: 8080