# yaml-language-server: $schema=https://raw.githubusercontent.com/open-telemetry/opentelemetry-helm-charts/main/charts/opentelemetry-collector/values.schema.json
# Helm values for https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector
apiVersion: apps/v1
mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

service:
  enabled: true

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    protocol: TCP

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318


  processors:
    batch: {}
  
    
  exporters:
    otlp/tempo:
      endpoint: tempo.observability:4317
      tls:
        insecure: true
    debug:
      verbosity: detailed

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/tempo, debug]
